name = "alphapebble"
main = ".open-next/worker.js"
compatibility_date = "2025-09-22"
compatibility_flags = ["nodejs_compat"]

# Static assets produced by OpenNext
assets = { directory = ".open-next/assets" }

# (optional) bind your domain directly here
# routes = [
#   { pattern = "alphapebble.io/*", zone_name = "alphapebble.io" }
# ]
