name = "alphapebble"
main = ".open-next/worker.js"
compatibility_date = "2025-09-22"
compatibility_flags = ["nodejs_compat"]

# keep ONLY this, delete any [site] block
assets = { directory = ".open-next/assets" }

# Optional domain binding
# routes = [{ pattern = "alphapebble.io/*", zone_name = "alphapebble.io" }]
