# wrangler.toml
name = "alphapebble"
main = ".open-next/worker.js"
compatibility_date = "2024-11-06"
assets = { directory = ".open-next/assets" }

# Add this block once you know the expected binding name:
[[r2_buckets]]
binding = "OPENNEXT_CACHE_BUCKET"   # <-- use the exact name the error/logs mention
bucket_name = "alphapebble-opennext-cache"
