name = "alphapebble"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[assets]]
bucket = ".open-next/assets"

[env.production]
routes = [
  { pattern = "*", zone_name = "alphapebble.io" },
]