name = "alphapebble"
main = ".open-next/worker.js"
compatibility_date = "2025-09-22"
compatibility_flags = ["nodejs_compat"]
assets = { directory = ".open-next/assets" }

[vars]
OPENNEXT_SERVER_WORKING_DIRECTORY = ".open-next/server-functions/default"
