name = "alphapebble"
main = ".open-next/worker.js"
compatibility_date = "2024-11-06"

# Serve the OpenNext-generated static assets
assets = { directory = ".open-next/assets" }

# (Optional) Environments. If you use them, deploy with --env=prod/dev.
# [env.prod]
# name = "alphapebble-prod"
# assets = { directory = ".open-next/assets" }
