name = "alphapebble"
main = ".opennext/standalone/server/index.js"
compatibility_date = "2025-09-22"
compatibility_flags = ["nodejs_compat"]

# Serve your static assets with the Worker
[site]
bucket = ".opennext/standalone/public"

# Optional: bind your domain directly here
# routes = [
#   { pattern = "alphapebble.io/*", zone_name = "alphapebble.io" }
# ]
